/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'

const TransactionsLazyRouteImport = createFileRoute('/transactions')()
const SettingsLazyRouteImport = createFileRoute('/settings')()
const DividendYieldLazyRouteImport = createFileRoute('/dividend-yield')()
const CompaniesIndexLazyRouteImport = createFileRoute('/companies/')()
const CompaniesCompanyIdLazyRouteImport = createFileRoute(
  '/companies/$companyId',
)()
const CompaniesCompanyIdIndexLazyRouteImport = createFileRoute(
  '/companies/$companyId/',
)()
const CompaniesCompanyIdDetailsLazyRouteImport = createFileRoute(
  '/companies/$companyId/details',
)()
const CompaniesCompanyIdReportIdLazyRouteImport = createFileRoute(
  '/companies/$companyId/$reportId',
)()

const TransactionsLazyRoute = TransactionsLazyRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/transactions.lazy').then((d) => d.Route))
const SettingsLazyRoute = SettingsLazyRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/settings.lazy').then((d) => d.Route))
const DividendYieldLazyRoute = DividendYieldLazyRouteImport.update({
  id: '/dividend-yield',
  path: '/dividend-yield',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/dividend-yield.lazy').then((d) => d.Route),
)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CompaniesIndexLazyRoute = CompaniesIndexLazyRouteImport.update({
  id: '/companies/',
  path: '/companies/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/companies/index.lazy').then((d) => d.Route),
)
const CompaniesCompanyIdLazyRoute = CompaniesCompanyIdLazyRouteImport.update({
  id: '/companies/$companyId',
  path: '/companies/$companyId',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/companies/$companyId.lazy').then((d) => d.Route),
)
const CompaniesCompanyIdIndexLazyRoute =
  CompaniesCompanyIdIndexLazyRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => CompaniesCompanyIdLazyRoute,
  } as any).lazy(() =>
    import('./routes/companies/$companyId/index.lazy').then((d) => d.Route),
  )
const CompaniesCompanyIdDetailsLazyRoute =
  CompaniesCompanyIdDetailsLazyRouteImport.update({
    id: '/details',
    path: '/details',
    getParentRoute: () => CompaniesCompanyIdLazyRoute,
  } as any).lazy(() =>
    import('./routes/companies/$companyId/details.lazy').then((d) => d.Route),
  )
const CompaniesCompanyIdReportIdLazyRoute =
  CompaniesCompanyIdReportIdLazyRouteImport.update({
    id: '/$reportId',
    path: '/$reportId',
    getParentRoute: () => CompaniesCompanyIdLazyRoute,
  } as any).lazy(() =>
    import('./routes/companies/$companyId/$reportId.lazy').then((d) => d.Route),
  )

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dividend-yield': typeof DividendYieldLazyRoute
  '/settings': typeof SettingsLazyRoute
  '/transactions': typeof TransactionsLazyRoute
  '/companies/$companyId': typeof CompaniesCompanyIdLazyRouteWithChildren
  '/companies': typeof CompaniesIndexLazyRoute
  '/companies/$companyId/$reportId': typeof CompaniesCompanyIdReportIdLazyRoute
  '/companies/$companyId/details': typeof CompaniesCompanyIdDetailsLazyRoute
  '/companies/$companyId/': typeof CompaniesCompanyIdIndexLazyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dividend-yield': typeof DividendYieldLazyRoute
  '/settings': typeof SettingsLazyRoute
  '/transactions': typeof TransactionsLazyRoute
  '/companies': typeof CompaniesIndexLazyRoute
  '/companies/$companyId/$reportId': typeof CompaniesCompanyIdReportIdLazyRoute
  '/companies/$companyId/details': typeof CompaniesCompanyIdDetailsLazyRoute
  '/companies/$companyId': typeof CompaniesCompanyIdIndexLazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dividend-yield': typeof DividendYieldLazyRoute
  '/settings': typeof SettingsLazyRoute
  '/transactions': typeof TransactionsLazyRoute
  '/companies/$companyId': typeof CompaniesCompanyIdLazyRouteWithChildren
  '/companies/': typeof CompaniesIndexLazyRoute
  '/companies/$companyId/$reportId': typeof CompaniesCompanyIdReportIdLazyRoute
  '/companies/$companyId/details': typeof CompaniesCompanyIdDetailsLazyRoute
  '/companies/$companyId/': typeof CompaniesCompanyIdIndexLazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dividend-yield'
    | '/settings'
    | '/transactions'
    | '/companies/$companyId'
    | '/companies'
    | '/companies/$companyId/$reportId'
    | '/companies/$companyId/details'
    | '/companies/$companyId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dividend-yield'
    | '/settings'
    | '/transactions'
    | '/companies'
    | '/companies/$companyId/$reportId'
    | '/companies/$companyId/details'
    | '/companies/$companyId'
  id:
    | '__root__'
    | '/'
    | '/dividend-yield'
    | '/settings'
    | '/transactions'
    | '/companies/$companyId'
    | '/companies/'
    | '/companies/$companyId/$reportId'
    | '/companies/$companyId/details'
    | '/companies/$companyId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DividendYieldLazyRoute: typeof DividendYieldLazyRoute
  SettingsLazyRoute: typeof SettingsLazyRoute
  TransactionsLazyRoute: typeof TransactionsLazyRoute
  CompaniesCompanyIdLazyRoute: typeof CompaniesCompanyIdLazyRouteWithChildren
  CompaniesIndexLazyRoute: typeof CompaniesIndexLazyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/transactions': {
      id: '/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof TransactionsLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dividend-yield': {
      id: '/dividend-yield'
      path: '/dividend-yield'
      fullPath: '/dividend-yield'
      preLoaderRoute: typeof DividendYieldLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/companies/': {
      id: '/companies/'
      path: '/companies'
      fullPath: '/companies'
      preLoaderRoute: typeof CompaniesIndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/companies/$companyId': {
      id: '/companies/$companyId'
      path: '/companies/$companyId'
      fullPath: '/companies/$companyId'
      preLoaderRoute: typeof CompaniesCompanyIdLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/companies/$companyId/': {
      id: '/companies/$companyId/'
      path: '/'
      fullPath: '/companies/$companyId/'
      preLoaderRoute: typeof CompaniesCompanyIdIndexLazyRouteImport
      parentRoute: typeof CompaniesCompanyIdLazyRoute
    }
    '/companies/$companyId/details': {
      id: '/companies/$companyId/details'
      path: '/details'
      fullPath: '/companies/$companyId/details'
      preLoaderRoute: typeof CompaniesCompanyIdDetailsLazyRouteImport
      parentRoute: typeof CompaniesCompanyIdLazyRoute
    }
    '/companies/$companyId/$reportId': {
      id: '/companies/$companyId/$reportId'
      path: '/$reportId'
      fullPath: '/companies/$companyId/$reportId'
      preLoaderRoute: typeof CompaniesCompanyIdReportIdLazyRouteImport
      parentRoute: typeof CompaniesCompanyIdLazyRoute
    }
  }
}

interface CompaniesCompanyIdLazyRouteChildren {
  CompaniesCompanyIdReportIdLazyRoute: typeof CompaniesCompanyIdReportIdLazyRoute
  CompaniesCompanyIdDetailsLazyRoute: typeof CompaniesCompanyIdDetailsLazyRoute
  CompaniesCompanyIdIndexLazyRoute: typeof CompaniesCompanyIdIndexLazyRoute
}

const CompaniesCompanyIdLazyRouteChildren: CompaniesCompanyIdLazyRouteChildren =
  {
    CompaniesCompanyIdReportIdLazyRoute: CompaniesCompanyIdReportIdLazyRoute,
    CompaniesCompanyIdDetailsLazyRoute: CompaniesCompanyIdDetailsLazyRoute,
    CompaniesCompanyIdIndexLazyRoute: CompaniesCompanyIdIndexLazyRoute,
  }

const CompaniesCompanyIdLazyRouteWithChildren =
  CompaniesCompanyIdLazyRoute._addFileChildren(
    CompaniesCompanyIdLazyRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DividendYieldLazyRoute: DividendYieldLazyRoute,
  SettingsLazyRoute: SettingsLazyRoute,
  TransactionsLazyRoute: TransactionsLazyRoute,
  CompaniesCompanyIdLazyRoute: CompaniesCompanyIdLazyRouteWithChildren,
  CompaniesIndexLazyRoute: CompaniesIndexLazyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
