/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'

const TransactionsLazyRouteImport = createFileRoute('/transactions')()
const SettingsLazyRouteImport = createFileRoute('/settings')()
const DividendYieldLazyRouteImport = createFileRoute('/dividend-yield')()
const CompaniesLazyRouteImport = createFileRoute('/companies')()

const TransactionsLazyRoute = TransactionsLazyRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/transactions.lazy').then((d) => d.Route))
const SettingsLazyRoute = SettingsLazyRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/settings.lazy').then((d) => d.Route))
const DividendYieldLazyRoute = DividendYieldLazyRouteImport.update({
  id: '/dividend-yield',
  path: '/dividend-yield',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/dividend-yield.lazy').then((d) => d.Route),
)
const CompaniesLazyRoute = CompaniesLazyRouteImport.update({
  id: '/companies',
  path: '/companies',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/companies.lazy').then((d) => d.Route))
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/companies': typeof CompaniesLazyRoute
  '/dividend-yield': typeof DividendYieldLazyRoute
  '/settings': typeof SettingsLazyRoute
  '/transactions': typeof TransactionsLazyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/companies': typeof CompaniesLazyRoute
  '/dividend-yield': typeof DividendYieldLazyRoute
  '/settings': typeof SettingsLazyRoute
  '/transactions': typeof TransactionsLazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/companies': typeof CompaniesLazyRoute
  '/dividend-yield': typeof DividendYieldLazyRoute
  '/settings': typeof SettingsLazyRoute
  '/transactions': typeof TransactionsLazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/companies'
    | '/dividend-yield'
    | '/settings'
    | '/transactions'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/companies' | '/dividend-yield' | '/settings' | '/transactions'
  id:
    | '__root__'
    | '/'
    | '/companies'
    | '/dividend-yield'
    | '/settings'
    | '/transactions'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CompaniesLazyRoute: typeof CompaniesLazyRoute
  DividendYieldLazyRoute: typeof DividendYieldLazyRoute
  SettingsLazyRoute: typeof SettingsLazyRoute
  TransactionsLazyRoute: typeof TransactionsLazyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/transactions': {
      id: '/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof TransactionsLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dividend-yield': {
      id: '/dividend-yield'
      path: '/dividend-yield'
      fullPath: '/dividend-yield'
      preLoaderRoute: typeof DividendYieldLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/companies': {
      id: '/companies'
      path: '/companies'
      fullPath: '/companies'
      preLoaderRoute: typeof CompaniesLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CompaniesLazyRoute: CompaniesLazyRoute,
  DividendYieldLazyRoute: DividendYieldLazyRoute,
  SettingsLazyRoute: SettingsLazyRoute,
  TransactionsLazyRoute: TransactionsLazyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
