/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'

const TransactionsLazyRouteImport = createFileRoute('/transactions')()
const DividendYieldLazyRouteImport = createFileRoute('/dividend-yield')()
const CurrencyLazyRouteImport = createFileRoute('/currency')()

const TransactionsLazyRoute = TransactionsLazyRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/transactions.lazy').then((d) => d.Route))
const DividendYieldLazyRoute = DividendYieldLazyRouteImport.update({
  id: '/dividend-yield',
  path: '/dividend-yield',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/dividend-yield.lazy').then((d) => d.Route),
)
const CurrencyLazyRoute = CurrencyLazyRouteImport.update({
  id: '/currency',
  path: '/currency',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/currency.lazy').then((d) => d.Route))
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/currency': typeof CurrencyLazyRoute
  '/dividend-yield': typeof DividendYieldLazyRoute
  '/transactions': typeof TransactionsLazyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/currency': typeof CurrencyLazyRoute
  '/dividend-yield': typeof DividendYieldLazyRoute
  '/transactions': typeof TransactionsLazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/currency': typeof CurrencyLazyRoute
  '/dividend-yield': typeof DividendYieldLazyRoute
  '/transactions': typeof TransactionsLazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/currency' | '/dividend-yield' | '/transactions'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/currency' | '/dividend-yield' | '/transactions'
  id: '__root__' | '/' | '/currency' | '/dividend-yield' | '/transactions'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CurrencyLazyRoute: typeof CurrencyLazyRoute
  DividendYieldLazyRoute: typeof DividendYieldLazyRoute
  TransactionsLazyRoute: typeof TransactionsLazyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/transactions': {
      id: '/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof TransactionsLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dividend-yield': {
      id: '/dividend-yield'
      path: '/dividend-yield'
      fullPath: '/dividend-yield'
      preLoaderRoute: typeof DividendYieldLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/currency': {
      id: '/currency'
      path: '/currency'
      fullPath: '/currency'
      preLoaderRoute: typeof CurrencyLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CurrencyLazyRoute: CurrencyLazyRoute,
  DividendYieldLazyRoute: DividendYieldLazyRoute,
  TransactionsLazyRoute: TransactionsLazyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
